### ISSUE TITLE
Lab 1 assignment: docker-compose lab may fail on Windows host

### ISSUE THREAD

**Issue by bertvv** [HoGentTIN/infra-labs#16]
Some students report problems with building the Docker compose application stack, because the filesystem doesn't allow certain operations (creating symlinks, e.g.). Make sure this is clear in the assignment. Workaround = copy the lab directory to /home/vagrant (maybe something to be added to the playbook to build the dockerlab VM).

**Comment by thomasaelbrecht** [comment]
Not an issue anymore as the lab 1 is now Jenkins.
