### ISSUE TITLE
Lab 1 extension

### ISSUE THREAD

**Issue by thomasaelbrecht** [HoGentTIN/infra-labs#22]
Let them experiment with a `Jenkinsfile` in the sample app repository to store their pipeline. This can be used as a mandatory step in the lab, as well as a possible extension.

**Comment by bertvv** [comment]
Also, it would be useful to have them build a pipeline for a .Net application...

**Comment by thomasaelbrecht** [comment]
I have some first steps for a new exercise about this, but it's getting too complex. I'll have a look at it after the exams.
