### ISSUE TITLE
Lab 2 Wordpress critical error

### ISSUE THREAD

**Issue by thomasaelbrecht** [HoGentTIN/infra-labs#24]
Some students get `There has been a critical error on this website` when installing the Wordpress role. Fix this issue in the role itself or write a note about this problem in the assignment.

The solution for this problem is to install the package `php-json`.

**Comment by bertvv** [comment]
I think I'm not going to keep maintaining that role. Since the wordpress package was deleted from the EPEL repo, it's much more complicated to reliably install Wordpress. But then, Wordpress should be replaced with something equivalent, preferably with a database backend.
